export const gpt_query = (brain, input, history, template) => {
  let query = `${brain} based on ${input} and ${
    history ? history : ""
  } following the normal physical exam template ${template}"`;

  let filter = `Add Filters  : `;

  filter += `Response should only be in HTML format. Also response should only generate result no other instructions.`;
  filter += "Response should not display that it is an html code like (```html ```)";
  filter += `Response should not have any color related styling.`;
  filter += `Response should not have any indication that this response is generated by an AI.`;
  filter += `Response should not be in table format.`;

  query += filter;


  // Change 1: reduce cluter for testing a simple prompt
  // query = `${brain} : ${input}.`

  // Change 2: Hard code SOAP command
  query = `${brain} objective, subjective, assessment and include differential diagnosis, plan and include suggested testing, instruction letter to patient. Split the physical exam and to vital signs Including BMI and organs examined individually: ${input}`


  query = `Based on ${input}, ${brain}: Please generate a comprehensive medical report with the following structure and details:

1. **Subjective Assessment**: Provide details of the patient's subjective symptoms and history.
2. **Objective**: Briefly describe the purpose of this document.
3. **Objective Assessment**: 
   - Split the physical examination details, including vital signs and BMI.
   - Describe organs examined individually.
4. **Assessment with Differential Diagnosis**: 
   - Use medical terminology to list possible differential diagnoses.
   - Provide an expansive list of conditions considered.
5. **Plan**: 
   - **Suggested Testing and Treatment**: Combine both testing and treatment suggestions into one section, utilizing specific medical terms. Ensure this includes recommended medications and further testing in detail.
   - **Instructions for Medications and Tests**: Integrate medications with tests in one comprehensive plan section, specifying dosages and frequencies where applicable.

**Formatting Requirements**:
- **Bold Font for AI Suggestions**: Highlight all suggestions generated by the AI in bold font to indicate they are AI-generated.

**Patient Instruction Letter**:
- At the end of the document, generate a letter of instruction to the patient. This letter should:
   - Use a formal letter format.
   - Summarize the plan, including any suggested testing and medications.
   - Provide clear instructions for the patient on the next steps.`


  return query;
};

// let filter = ` resposne should be in html formay based on the data provided ans should only be in html format, also make sure the data is related to medical field and if there is an error it should highlight it only html format. if there is some query where you are not able to answer just return in html tag you were not able to find the answer.`;
// filter += `Reponse generated should not have extra instructions. for user to read such as \`\`\` Please replace the placeholder text with your actual data and error messages `;
// filter += `there should be no text color style applied to response.`
// filter += 'there should be no similar content in response \`\`\` The final HTML file when rendered would provide a neatly organized clinical management plan. However, this information should be used as a guideline and does not substitute for professional medical advice. '
// filter += 'there should be no table in response.'
// filter += 'remove if any "As an AI" type of response'
