export const gpt_query = (brain, input, history, template) => {
  let query = `${brain} based on ${input} and ${
    history ? history : ""
  } following the normal physical exam template ${template}"`;

  let filter = `Add Filters  : `;

  filter += `Response should only be in HTML format. Also response should only generate result no other instructions.`;
  filter += "Response should not display that it is an html code like (```html ```)";
  filter += `Response should not have any color related styling.`;
  filter += `Response should not have any indication that this response is generated by an AI.`;
  filter += `Response should not be in table format.`;

  query += filter;


  // Change 1: reduce cluter for testing a simple prompt
  // query = `${brain} : ${input}.`

  // Change 2: Hard code SOAP command
  //  query = `${brain} objective, subjective, assessment and include differential diagnosis, plan and include suggested testing, instruction letter to patient. Split the physical exam and to vital signs Including BMI and organs examined individually: ${input}`


query = `${brain} Document as a physician would in a chief complaint, subjective, objective, labs and x-rays, assessment, and plan format in that order. 
Start by documenting patient’s name, date of birth, and date of visit, physician's name at the top of the report.
The Subjective should be in paragraph form, always starting with age and gender.
Document ROS following subjective in bullet format, PMH after ROS in bullet format, social history after PMH in bullet format, home medications following PMH in bullet format, and allergies following home medications in bullet format.
The objective in bullet points format, including BMI with the vital signs section. Leave a blank line between BMI and the rest of the physical examination.

Normal Physical Exam Template:
General Appearance: The patient appears ${anomalies.generalAppearance || '[well-developed, well-nourished/other observations]'}. There are no signs of distress or acute discomfort. The patient is oriented to person, place, and time.
HEENT (Head, Eyes, Ears, Nose, Throat):
• Head: ${anomalies.head || 'Normocephalic, atraumatic'}.
• Eyes: ${anomalies.eyes || 'Pupils equal, round, and reactive to light. Extraocular movements intact. No evidence of conjunctival injection or discharge'}.
• Ears: ${anomalies.ears || 'Bilateral canals patent, tympanic membranes intact'}.
• Nose: ${anomalies.nose || 'Nasal mucosa moist without discharge'}.
• Throat: ${anomalies.throat || 'Oropharynx clear without erythema or exudates'}.
Chest:
• Inspection: ${anomalies.chestInspection || 'Chest wall symmetrical, no deformities'}.
• Palpation: ${anomalies.chestPalpation || 'No tenderness or masses. Chest expansion equal bilaterally'}.
• Percussion: ${anomalies.chestPercussion || 'Resonant note'}.
• Auscultation: ${anomalies.chestAuscultation || 'Breath sounds clear bilaterally, no wheezes, rales, or rhonchi'}.
Heart:
• Inspection/Palpation: ${anomalies.heartInspectionPalpation || 'No visible or palpable precordial pulsations'}.
• Auscultation: ${anomalies.heartAuscultation || 'Regular rate and rhythm. S1 and S2 audible, with no murmurs, rubs, or gallops'}.
Abdomen:
• Inspection: ${anomalies.abdomenInspection || 'Abdomen flat, no distention or masses'}.
• Palpation: ${anomalies.abdomenPalpation || 'Soft, non-tender, no guarding or rigidity. No palpable hepatosplenomegaly'}.
• Auscultation: ${anomalies.abdomenAuscultation || 'Bowel sounds present in all quadrants'}.
Extremities:
• Upper Extremities: ${anomalies.upperExtremities || 'No clubbing, cyanosis, or edema. Full range of motion'}.
• Lower Extremities: ${anomalies.lowerExtremities || 'No clubbing, cyanosis, or edema. Full range of motion. Pulses strong and equal bilaterally'}.
Skin:
• Color: ${anomalies.skinColor || '[appropriate for ethnicity]'}.
• Temperature: ${anomalies.skinTemperature || 'Skin warm and dry'}.
• Lesions: ${anomalies.skinLesions || 'No rashes, lesions, or abnormal pigmentation'}.
Musculoskeletal:
• Gait: ${anomalies.gait || 'Normal, no limp'}.
• Strength: ${anomalies.strength || '5/5 strength in all extremities'}.
• Joint Exam: ${anomalies.jointExam || 'No swelling, tenderness, or deformities noted'}.
Neurology:
• Mental Status: ${anomalies.mentalStatus || 'Alert and oriented to person, place, and time'}.
• Cranial Nerves: ${anomalies.cranialNerves || 'Intact'}.
• Motor Exam: ${anomalies.motorExam || 'Strength 5/5 throughout'}.
• Sensory Exam: ${anomalies.sensoryExam || 'Sensation intact'}.
• Reflexes: ${anomalies.reflexes || 'Deep tendon reflexes 2+ and symmetrical'}.

If Physical exam is other than normal, document only the abnormal findings for the examined organ.
Add differential diagnosis using medical terms and an expansive list, and suggest further testing in a specific way using medical terms and recommend medications in a specific and expansive way.
Combine suggested testing and suggested treatment in one section with plan.
Highlight in bold font all AI suggestions indicating they were generated by the AI.
At the end, generate a letter of instruction to the patient using a formal letter format.

End each report with Ahmed Badr, MD, FCCP
`;





  return query;
};

// let filter = ` resposne should be in html formay based on the data provided ans should only be in html format, also make sure the data is related to medical field and if there is an error it should highlight it only html format. if there is some query where you are not able to answer just return in html tag you were not able to find the answer.`;
// filter += `Reponse generated should not have extra instructions. for user to read such as \`\`\` Please replace the placeholder text with your actual data and error messages `;
// filter += `there should be no text color style applied to response.`
// filter += 'there should be no similar content in response \`\`\` The final HTML file when rendered would provide a neatly organized clinical management plan. However, this information should be used as a guideline and does not substitute for professional medical advice. '
// filter += 'there should be no table in response.'
// filter += 'remove if any "As an AI" type of response'
